---
title: "testpsignifit"
format: pdf
---

This is designed to test running of psignifit in a docker container on github.

```{r}

library(reticulate)

# use_miniconda('r-reticulate')
install_python(version='3.12')
# use_python_version("3.9.1")

virtualenv_create('pfitenv',version="3.12")

py_install('https://github.com/wichmann-lab/python-psignifit/zipball/master')

```


```{python}

# pip install https://github.com/wichmann-lab/python-psignifit/zipball/master

import psignifit as ps

C = ps.utils.my_norminv(1-0.05,0,1) - ps.utils.my_norminv(0.05,0,1)

#        levels, n-correct,   n-total
data = [[0.0010,   45.0000,   90.0000],
        [0.0015,   50.0000,   90.0000],
        [0.0020,   44.0000,   90.0000],
        [0.0025,   44.0000,   90.0000],
        [0.0030,   52.0000,   90.0000],
        [0.0035,   53.0000,   90.0000],
        [0.0040,   62.0000,   90.0000],
        [0.0045,   64.0000,   90.0000],
        [0.0050,   76.0000,   90.0000],
        [0.0060,   79.0000,   90.0000],
        [0.0070,   88.0000,   90.0000],
        [0.0080,   90.0000,   90.0000],
        [0.0100,   90.0000,   90.0000]]

result = ps.psignifit(data, experiment_type='2AFC')
print(result.get_parameters_estimate())

```

```{r}

  ps <- import('psignifit')
  C <- ps$utils$my_norminv(1-0.05,0,1) - ps$utils$my_norminv(0.05,0,1)

```

C = `r C`

This indicates it is working.
